site_name: OlivOS官方文档
repo_name: OlivOS-Team/OlivOS
repo_url: https://github.com/OlivOS-Team/OlivOS
edit_uri: ""

theme:
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - redirects:
      redirect_maps:
        'OlivOS_README.md': 'Intro.md'
        'OlivOS_UserDoc_Account.md': 'User/Account.md'
        'OlivOSOnebotV11.md': 'Protocol/OlivOSOnebotV11.md'
        'OlivOS_DevDoc_Plugin_Template.md': 'DevPlugin/Template.md'
        'OlivOS_DevDoc_Event.md': 'DevPlugin/Event.md'
        'OlivOS_DevDoc_Plugin_API.md': 'DevPlugin/API.md'
        'OlivOS_DevDoc_Note.md': 'DevPlugin/Note.md'
        'OlivOS_DevDoc_Open_Source.md': 'DevGuild/OpenSource.md'
        'OlivOS_DevDoc_Technology.md': 'DevGuild/Technology.md'
        'EcoSystem.md': 'Community/EcoSystem.md'
        'EcoSystem/EcoSystem.md': 'Community/EcoSystem.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 使用:
    - 基础使用:
      - 开始使用: User/Intro.md
      - 账号管理: User/Account.md
      - OPQ注意事项: User/OPQ.md
    - 协议端:
      - OnebotV11: Protocol/OlivOSOnebotV11.md
  - 开发:
    - 开发手册: Intro.md
    - 插件开发:
      - 插件模板: DevPlugin/Template.md
      - 框架事件: DevPlugin/Event.md
      - 插件接口: DevPlugin/API.md
      - 用户模块接口: DevPlugin/UserModule.md
      - 开发技巧: DevPlugin/Note.md
    - 开发指引:
      - 开源协议: DevGuild/OpenSource.md
      - 技术选型: DevGuild/Technology.md
      - 开发环境: DevGuild/Env.md
      - 文件结构: DevGuild/File.md
      - 组件框架: DevGuild/Framework.md
      - 插件架构: DevGuild/Plugin.md
      #- 产品模型
      #- 实现细节
    - 社区指引:
      - 阿罗悖论: CommunityGuild/Elect.md
  - 生态: Community/EcoSystem.md
  - OlivaDice: https://wiki.dice.center/
  - 论坛: https://forum.olivos.run
  - 捐助: https://afdian.net/@OlivOS
