site_name: OlivOS官方文档
repo_name: OlivOS-Team/OlivOS
repo_url: https://github.com/OlivOS-Team/OlivOS
edit_uri: ""

theme:
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
plugins:
  - search:
      separator: '[\s\u200b\-]'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 开发手册:
    - 开发手册: OlivOS_README.md
    - 基础使用:
      - 账号管理: OlivOS_UserDoc_Account.md
    - 协议端:
      - OnebotV11: OlivOSOnebotV11.md
    - 插件开发:
      - 插件模板: OlivOS_DevDoc_Plugin_Template.md
      - 框架事件: OlivOS_DevDoc_Event.md
      - 插件接口: OlivOS_DevDoc_Plugin_API.md
      - 开发技巧: OlivOS_DevDoc_Note.md
    - 实现原理:
      - 开源协议: OlivOS_DevDoc_Open_Source.md
      - 技术选型: OlivOS_DevDoc_Technology.md
      #- 产品模型
      #- 实现细节
  - 生态: EcoSystem.md
  - 论坛: https://forum.olivos.run
  - 捐助: https://afdian.net/@OlivOS
